steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/brahmilator:$COMMIT_SHA'
      - ./brahmi_backend
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/brahmilator:$COMMIT_SHA'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - brahmilator
      - '--image'
      - 'gcr.io/$PROJECT_ID/brahmilator:$COMMIT_SHA'
      - '--region'
      - asia-southeast1
      - '--platform'
      - managed
      - '--timeout'
      - 15m
images:
  - 'gcr.io/$PROJECT_ID/brahmilator:$COMMIT_SHA'
